sudo: required
services:
    - docker
before_install:
    - docker build -t brunoestrada/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true brunoestrada/docker-react npm run test
deploy:
    provider: elascticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-606695939007"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACESS_KEY
    secret_access_key: $AWS_SECRET_KEY
